model:
  type: resnet34
  noise_type: aggre
  dataset: cifar10

dataset: cifar10
aug: autoaug_cifar10   # autoaug_extend
cutout: 16
batch: 320
batch_unsup: 80
ratio_unsup: 0.4
ratio_mode: 'constant'
epoch: 110
lr: 0.0002
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 10
    epoch: 2
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005

random_state: 0
train_labels: '../../SimiFeat/results/rank1_cifar10_aggre_label15.0_label.npy'
unsup_idx: '../../SimiFeat/results/rank1_cifar10_aggre_label15.0_pred.npy'
pretrain: ''

tqdm_disable: False


